### ISSUE TITLE
Packer/QEMU + Ubuntu 20.04 : Problem partion resize when instantiated image on Openstack

### ISSUE THREAD

**Issue by wbessard** [hashicorp/packer#10279]
Hi everybody,

I send you this message because I have a problem with partition size when I instantiated a VM in Openstack with my private image.
I used **Packer 1.2.4** and **Qemu 1.5.3** to create a **QCOW2** image of **Ubuntu 20.04**. When I uploded it in Openstack and tried to instantiate a VM, my main partition is not full (23G in follow example) and depend on the ```disk_size``` option that I set in packer file. As you can see with 2 follows command result, I have a wrong partitioning.
I would like that when an user create a VM with **X** Gb disk, that the main partition size equal **X** Gb.
I joined you below the two files used by packer. Help me please !

``` bash
user@ubuntu-server:~$ lsblk
NAME                      MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop0                       7:0    0   55M  1 loop /snap/core18/1880
loop1                       7:1    0 29,9M  1 loop /snap/snapd/8542
loop2                       7:2    0 71,3M  1 loop /snap/lxd/16099
vda                       252:0    0   23G  0 disk 
├─vda1                    252:1    0    1M  0 part 
├─vda2                    252:2    0    1G  0 part /boot
└─vda3                    252:3    0    7G  0 part 
  └─ubuntu--vg-ubuntu--lv 253:0    0    7G  0 lvm  /
user@ubuntu-server:~$ df -h
Filesystem                         Size  Used Avail Use% Mounted on
udev                               952M     0  952M   0% /dev
tmpfs                              199M  996K  198M   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv  6,9G  3,4G  3,1G  53% /
tmpfs                              994M     0  994M   0% /dev/shm
tmpfs                              5,0M     0  5,0M   0% /run/lock
tmpfs                              994M     0  994M   0% /sys/fs/cgroup
/dev/vda2                          976M  104M  806M  12% /boot
/dev/loop0                          30M   30M     0 100% /snap/snapd/8542
/dev/loop1                          72M   72M     0 100% /snap/lxd/16099
/dev/loop2                          55M   55M     0 100% /snap/core18/1880
tmpfs                              199M     0  199M   0% /run/user/1000
```

## MY PACKER FILES
# builder.json
``` json
{
  "builders": [
    {
      "type": "qemu",
      "qemu_binary":"/usr/libexec/qemu-kvm",
      "iso_checksum": "{{ user `iso_checksum` }}",
      "iso_checksum_type": "{{ user `iso_checksum_type` }}",
      "iso_url": "{{ user `iso_url` }}",

      "http_directory": "http",
      "output_directory": "{{ user `tmp_directory` }}",
      "vm_name": "{{ user `vm_name` }}",
      "format": "qcow2",
      "headless": "{{user `headless`}}",
      
      "accelerator": "kvm",
      "boot_wait": "1s",
      "boot_command": [
        "<enter><enter><f6><esc><wait> ",
        "autoinstall net.ifnames=0 biosdevname=0 ip=dhcp ipv6.disable=1 ds=nocloud-net;s=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ ",
        "<enter>"
      ],

      "ssh_password": "{{ user `ssh_password` }}",
      "ssh_username": "{{ user `ssh_username` }}",
      "ssh_timeout": "{{user `ssh_timeout`}}",
      "ssh_handshake_attempts": 500,
      "shutdown_command": "echo 'PACKER' | sudo shutdown -P now",
      
      "net_device": "virtio-net",
      
      "disk_size": "8192",
      "disk_image": "false",
      "disk_interface": "virtio",
      "disk_compression": "true",
      "qemuargs": [
        ["-m", "{{user `memory`}}"],
        ["-smp", "{{user `cpus`}}"]
      ]
    }
  ],
  "provisioners": [
   ],
  "post-processors": [
   ],
  "variables": {
    "compression_level": "9",
    "output_directory": "/data/packer/output",
    "tmp_directory": "dist",
    "cpus": "1",
    "headless": "true",
    "memory": "1024",
    "ssh_timeout": "60m",
    "ssh_password": "MYUSERNAME",
    "ssh_username": "MYPASSWORD",
    "vm_name": "ubuntu-server",
    "boot_command_prefix": "<esc><esc><esc><enter>",
    "iso_url": "/iso/ubuntu-20.04.1-live-server-amd64.iso",
    "iso_checksum": "443511f6bf12402c12503733059269a2e10dec602916c0a75263e5d990f6bb93",
    "iso_checksum_type": "sha256",
    "description": "Ubuntu 20.04 Server",
    "short_description": "Ubuntu 20.04"
  }
}
```

# user-data
``` yaml
#cloud-config
autoinstall:
  version: 1
  locale: en_US
  keyboard:
    layout: us

  packages:
    - cloud-init
    - cloud-utils
    - cloud-initramfs-growroot
    - cloud-guest-utils
  
  ssh:
    allow-pw: yes
    install-server: true
    
  identity:
    hostname: ubuntu-server
    password: "$MYENCRYPTEDPASSWORD"
    username: $MYUSERNAME
    realname: "Ubuntu User"
   
  network:
    network:
      version: 2
      ethernets:
        ens33:
          dhcp4: true
          dhcp-identifier: mac
        eth0:
          dhcp4: true
          dhcp-identifier: mac
 
  user-data:
    disable_root: false
    timezone: Europe/Paris
  
  late-commands:
    - 'sed -i "s/^#*\(send dhcp-client-identifier\).*$/\1 = hardware;/" /target/etc/dhcp/dhclient.conf'
    - 'sed -i "s/dhcp4: true/&\n      dhcp-identifier: mac/" /target/etc/netplan/00-installer-config.yaml'
    - echo 'cloudadm ALL=(ALL) NOPASSWD:ALL' > /target/etc/sudoers.d/cloudadm
```
