### ISSUE TITLE
GCP GitLab CI Runner get timout v1.6.6

### ISSUE THREAD

**Issue by lukas9393** [hashicorp/packer#10406]
I run packer on an official GitLab CI runner to create an image with the builder googlecompute. I give Packer a service_account with the environment variable GOOGLE_APPLICATION_CREDENTIALS that has access to my GCP project. 

With packer v1.6.5 I can build an image. But now with 1.6.6 I get a timeout.

```
packer build -force packer/runner.json
googlecompute: output will be in this color.
Build 'googlecompute' errored after 30 seconds 2 milliseconds: Get "http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/email": dial tcp 169.254.169.254:80: i/o timeout
==> Wait completed after 30 seconds 2 milliseconds
```

The reason is that packer tries to find out an email from the metadata of the instance. 

The request results in a timeout, because the service account I provide has no rights to this metadata. If packer uses the service account of the instance for this request, then it also has no access, because probably the operator of gitlab does not allow this access.

Packer has no access to the metadata of the instance itself on which the runner is running.

_Originally posted by @lukas9393 in https://github.com/hashicorp/packer/pull/10360#discussion_r545795998_

_packer/runner.json_
```
{
  "variables": {
    "project_id": "{{env `GCP_PROJECT`}}",
    "image_name": "{{env `IMAGE_NAME`}}"
  },
  "builders": [
    {
      "type": "googlecompute",
      "project_id": "{{user `project_id`}}",
      "machine_type": "n1-standard-1",
      "source_image_family": "debian-10",
      "region": "europe-west1",
      "zone": "europe-west1-b",
      "image_description": "Default image",
      "image_name": "{{user `image_name`}}",
      "disk_size": 10,
      "ssh_username": "ubuntu"
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "script": "packer/install-ansible.sh"
    },
    {
      "type": "ansible-local",
      "playbook_file": "packer/ansible/runner-playbook.yml",
      "playbook_dir": "packer/ansible/"
    }
  ]
}
```

_.gitlab-ci.yml_
```
stages:
  - build

build-image:
  stage: build
  image:
    name: hashicorp/packer:1.6.6
    entrypoint: ["/bin/bash", "-l", "-c"]
  script:
    - IMAGE_NAME="default-$CI_PIPELINE_IID"
    - packer build -force packer/runner.json

```
