### ISSUE TITLE
Github action for packer

### ISSUE THREAD

**Issue by caulagi** [hashicorp/packer#10452]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Is there any plan to provide a github action similar to terraform like https://github.com/hashicorp/setup-terraform?

#### Use Case(s)

I would like to run `packer validate` and `packer fmt` from CI pipeline

#### Potential configuration

```
steps:
- uses: hashicorp/setup-packer@v1
  with:
    packer_version: 1.6.6
```

#### Potential References

https://github.com/hashicorp/setup-terraform

**Comment by nywilken** [comment]
Hi there @caulagi  have you seen the work done at https://github.com/marketplace/actions/packer-github-actions?

It might be exactly what you are looking for. Let us know.

**Comment by caulagi** [comment]
@nywilken I see that this issue was labelled as docs. Is this the 'official' recommendation for running packer with github actions? I have a few issues currently that I am going to raise issues for with `operatehappy/packer-github-actions` repository  - 

* Seems to support old packer (1.5.5)
* No option to specify the version. It would be nice to be able to do - 
    ```
    steps:
    - uses: <provider>/setup-packer@v1
       with:
         packer_version: 1.6.6
    ```
* Handling of target is a bit weird with a default of `artifacts.pkr.json`
