### ISSUE TITLE
Ubuntu 20.04.3 - Build with hcl

### ISSUE THREAD

**Issue by talheim-it** [hashicorp/packer#11275]
Hello Community!

I tried to create a new Ubuntu20.04.3 box by myself. The builder runs completely through without issues what I can see.

But when I am adding it to vagrant, it is not coming up, no ssh connection can be established. I guess I did anything wrong in the packer build so I wanted to share it first before digging into vagrant, since the build for CentOS, Fedora, AlmaLinux, RockyLinux worked.

Build with:
Fedora 34 Workstation
Packer v1.7.5

**ubuntu2004.pkr.hcl:**
```
##################################################################################
# VARIABLES
##################################################################################

variable "vm_ssh_username" {
  type    = string
  description = "The username to use to authenticate over SSH."
  default = "ubuntu"
}

variable "vm_ssh_password" {
  type    = string
  description = "The plaintext password to use to authenticate over SSH."
  default = "ubuntu"
}

variable "iso_url" {
  type    = string
  description = "The path on the source vSphere datastore for ISO images."
  default = ""
}

variable "iso_file" {
  type = string
  description = "The file name of the guest operating system ISO image installation media."
  default = ""
}

variable "iso_checksum" {
  type    = string
  description = "The SHA-512 checkcum of the ISO image."
  default = ""
}

variable "http_directory" {
  type    = string
  description = "Directory of config files(user-data, meta-data)."
  default = ""
}

variable "vm_firmware" {
  type    = string
  description = "The virtual machine firmware. (e.g. 'bios' or 'efi')"
  default = ""
}

variable "vm_cpu_cores" {
    type = number
    description = "Number of CPU cores for the VM"
    default = 2
}

variable "vm_mem_size" {
    type = number
    description = "Size of the virtual memory im MB"
    default = 2048
}

variable "vm_disk_size" {
    type = number
    description = "The size of the virtual disk in MB"
}

variable "vm_host_name" {
    type = string
    description = "Name of the virtual machine"
    default = "Ubuntu2004"
}

variable "vm_output_directory" {
    type = string
    description = "Location where the box image is exported to"
    default = "/home/username/Development/images/libvirt/Ubuntu2004"
}

##################################################################################
# SOURCE
##################################################################################

source "qemu" "ubuntu2004" {
  # VM resource parameters
  cpus              = "${var.vm_cpu_cores}"
  memory            = "${var.vm_mem_size}"
  disk_interface    = "virtio"
  disk_size         = "${var.vm_disk_size}"
  iso_url           = "${var.iso_url}"
  iso_checksum      = "${var.iso_checksum}"
  output_directory  = "${var.vm_output_directory}"
  shutdown_command  = "echo '${var.vm_ssh_password}' | sudo -S shutdown -P now"
  format            = "qcow2"
  accelerator       = "kvm"
  http_directory    = "${var.http_directory}"
  ssh_username      = "${var.vm_ssh_username}"
  ssh_password      = "${var.vm_ssh_password}"
  ssh_handshake_attempts = "100"
  vm_name           = "${var.vm_host_name}"
  net_device        = "virtio-net"
  net_bridge        = "virbr0"
  cd_files          = ["./http/user-data", "./http/meta-data"]
  cd_label          = "cidata"
  boot_wait         = "2s"
  qemu_binary       = "/usr/bin/qemu-system-x86_64"
  boot_command      = [
    "<enter><wait2><enter><wait><f6><esc><wait>",
    " autoinstall<wait2> ds=nocloud;",
    "<wait><enter>"
  ]
}

build {
  sources = ["source.qemu.ubuntu2004"]

  post-processor "vagrant" {}
}
```

File: variables.pkr.hcl:
```
##################################################################################
# VARIABLES
##################################################################################

vm_cpu_cores          = 2
vm_mem_size           = 4096
vm_disk_size          = 40000

vm_ssh_username       = "vagrant"
vm_ssh_password       = "vagrant"

http_directory        = "http"

iso_url               = "https://releases.ubuntu.com/20.04/ubuntu-20.04.3-live-server-amd64.iso"
iso_checksum          = "file:https://releases.ubuntu.com/20.04/SHA256SUMS"

vm_output_directory   = "/home/username/Development/images/libvirt/Ubuntu2004"
```

File: http/user-data:
```
#cloud-config
autoinstall:
  version: 1
  user-data:
    users:
      - name: vagrant
        passwd: $6$ZTEqV3tdvUeoVgC7$MLAObfljDKhULgtoq6Hx.SC.1dD8bo84PqH8poZzcJqo9czDYutON68/PjAmxVK3BQU3N.fB4G9MuZZ5OQ3GF1
        groups: [adm, cdrom, dip, plugdev, lxd, sudo]
        lock-passwd: false
        sudo: ALL=(ALL) NOPASSWD:ALL
        shell: /bin/bash
        ssh_authorized_keys:
          - examplekey
  locale: en_US
  keyboard:
      layout: de
      variant: de
  network:
    version: 2
    ethernets:
        ens3:
          dhcp4: true
  storage:
    layout:
      name: direct
    config:
      - type: disk
        id: disk0
        match:
          size: largest
      - type: partition
        id: boot-partition
        device: disk0
        size: 500M
      - type: partition
        id: root-partition
        device: disk0
        size: -1
  ssh:
    install-server: true
    allow-pw: true
  packages:
      - bash-completion
      - wget
      - vim
      - curl
      - qemu-guest-agent
```
