### ISSUE TITLE
Image based on latest Amazon Linux 2 AMI does not function when applied to EC2 instance.

### ISSUE THREAD

**Issue by Willbly** [hashicorp/packer#11623]
I am attempting to spin up an EC2 instance with an image created by Packer with no changes, based on the latest Amazon Linux 2 AMI (HVM) - Kernel 5.10, SSD Volume Type - ami-07c3ee614638f120d (64-bit x86) AMI. The EC2 starts but is completely unreachable by any means. When using the exact same configuration but using the AMI directly instead of created through Packer, everything works fine.

This is my Packer configuration:
```
{
  "builders": [
    {
      "type": "amazon-ebs",
      "profile": "packer-build",
      "region": "ap-southeast-2",
      "instance_type": "t3.micro",
      "source_ami": "ami-07c3ee614638f120d",
      "ssh_username": "ec2-user",
      "ami_name": "latest-amz2-packer-build",
      "vpc_id": <irrelevant>,
      "subnet_id": <irrelevant>,
      "associate_public_ip_address": "true",
    }
  ]
}
```

This is the simple EC2 CloudFormation template I've been using to test:
```
AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      SecurityGroups: [!Ref 'InstanceSecurityGroup']
      KeyName: !Ref 'KeyName'
      ImageId: <The Packer generated AMI ID>
      Tags:
        - Key: Name
          Value: "Packer Test"
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
```

I'm completely unable to SSH on when using the Packer created image but can access fine when using the source AMI directly. It also works fine with a Packer created image based on the Amazon Linux 2 AMI that was most recent in December 2021.
