### ISSUE TITLE
wget salt-bootstrap hanging salt provisioner

### ISSUE THREAD

**Issue by ghost** [hashicorp/packer#1171]
I'm running the salt provisioner to build a virtualbox image and it's hanging at the following:

```
virtualbox-iso: Installing Salt with command &{wget -O - http://bootstrap.saltstack.org | sudo sh -s  <nil> <nil> <nil> %!s(bool=false) %!s(int=0) %!s(chan struct {}=<nil>) {%!s(int32=0) %!s(uint32=0)}}
    virtualbox-iso: --2014-05-13 13:34:26--  http://bootstrap.saltstack.org/
    virtualbox-iso: Resolving bootstrap.saltstack.org (bootstrap.saltstack.org)... 74.208.29.198
    virtualbox-iso: Connecting to bootstrap.saltstack.org (bootstrap.saltstack.org)|74.208.29.198|:80... [sudo] password for vagrant: connected.
    virtualbox-iso: HTTP request sent, awaiting response... 302 Found
    virtualbox-iso: Location: https://raw.github.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh [following]
    virtualbox-iso: --2014-05-13 13:34:26--  https://raw.github.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh
    virtualbox-iso: Resolving raw.github.com (raw.github.com)... 199.27.78.133
    virtualbox-iso: Connecting to raw.github.com (raw.github.com)|199.27.78.133|:443... connected.
    virtualbox-iso: HTTP request sent, awaiting response... 301 Moved Permanently
    virtualbox-iso: Location: https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh [following]
    virtualbox-iso: --2014-05-13 13:34:26--  https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh
    virtualbox-iso: Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.27.78.133
    virtualbox-iso: Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.27.78.133|:443... connected.
    virtualbox-iso: HTTP request sent, awaiting response... 200 OK
    virtualbox-iso: Length: 158472 (155K) [text/plain]
    virtualbox-iso: Saving to: ‘STDOUT’
    virtualbox-iso:
```

If I run the following on a Mac OS X terminal, it also hangs:

```
$ wget -O - http://bootstrap.saltstack.org | sudo sh -s
--2014-05-13 10:06:57--  http://bootstrap.saltstack.org/
Resolving bootstrap.saltstack.org... Password:74.208.29.198
Connecting to bootstrap.saltstack.org|74.208.29.198|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.github.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh [following]
--2014-05-13 10:06:57--  https://raw.github.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh
Resolving raw.github.com... 199.27.76.133
Connecting to raw.github.com|199.27.76.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh [following]
--2014-05-13 10:06:58--  https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh
Resolving raw.githubusercontent.com... 199.27.76.133
Connecting to raw.githubusercontent.com|199.27.76.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 158472 (155K) [text/plain]
Saving to: 'STDOUT'

 0% [                                                                                                    ] 0           --.-K/s  
```

The progress bar never proceeds. I can wget the file without piping it to `sh` with no problem.

If I run the same command but point it to the new location of salt-bootstrap, on Mac OS X I get an error indicating that wget piping to shell is not supported on Darwin. If I point wget to the original URL, it hangs at 0% progress. I'm trying to build an Ubuntu 14.04 image, so maybe it's not supported there--I will try on an older Ubuntu version and see what I get.

Either way, maybe splitting up the command--download, run, remove--would make this more stable?
