### ISSUE TITLE
 vmware-iso is not recognized as the name of a cmdlet, function, script file, or operable

### ISSUE THREAD

**Issue by carlskii** [hashicorp/packer#2785]
Hi,

I've defined a powershell provisioner that looks like this:

```
{
      "type": "powershell",
      "inline": ["Add-WindowsFeature -Name ad-domain-services -IncludeAllSubFeature -IncludeManagementTools",
                 "Add-WindowsFeature -Name dns -IncludeAllSubFeature -IncludeManagementTools",
                 "Add-WindowsFeature -Name gpmc -IncludeAllSubFeature -IncludeManagementTools"
                ]
    }
```

However even though it seems to run OK it seems to be throwing some strange messages. I'm using VMware Fusion 8, so I'm wondering if thats the problem.

```
==> vmware-iso: Provisioning with Powershell...
==> vmware-iso: Provisioning with shell script: /var/folders/b4/grsjj0d52t33m9jvc6g8_5440000gn/T/packer-powershell-provisioner613945982
    vmware-iso: :PACKER_BUILDER_TYPE=vmware-iso : The term ':PACKER_BUILDER_TYPE=vmware-iso'
    vmware-iso: is not recognized as the name of a cmdlet, function, script file, or operable
    vmware-iso: program. Check the spelling of the name, or if a path was included, verify
    vmware-iso: that the path is correct and try again.
    vmware-iso: At line:1 char:5
    vmware-iso: + & { :PACKER_BUILDER_TYPE="vmware-iso"; :PACKER_BUILD_NAME="vmware-iso";
    vmware-iso: c:/Windo ...
    vmware-iso: +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    vmware-iso: + CategoryInfo          : ObjectNotFound: (:PACKER_BUILDER_TYPE=vmware-iso
    vmware-iso: :String) [], CommandNotFoundException
    vmware-iso: + FullyQualifiedErrorId : CommandNotFoundException
    vmware-iso:
    vmware-iso: :PACKER_BUILD_NAME=vmware-iso : The term ':PACKER_BUILD_NAME=vmware-iso' is
    vmware-iso: not recognized as the name of a cmdlet, function, script file, or operable
    vmware-iso: program. Check the spelling of the name, or if a path was included, verify
    vmware-iso: that the path is correct and try again.
    vmware-iso: At line:1 char:40
    vmware-iso: + & { :PACKER_BUILDER_TYPE="vmware-iso"; :PACKER_BUILD_NAME="vmware-iso";
    vmware-iso: c:/Windo ...
    vmware-iso: +                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    vmware-iso: + CategoryInfo          : ObjectNotFound: (:PACKER_BUILD_NAME=vmware-iso:S
    vmware-iso: tring) [], CommandNotFoundException
    vmware-iso: + FullyQualifiedErrorId : CommandNotFoundException
    vmware-iso:
    vmware-iso:
    vmware-iso: Success Restart Needed Exit Code      Feature Result
    vmware-iso: ------- -------------- ---------      --------------
    vmware-iso: True    No             Success        {Active Directory Domain Services, Gro...
    vmware-iso: WARNING: The following recommended condition is not met for DNS: No static IP
    vmware-iso: addresses were found on this computer. If the IP address changes, clients might
    vmware-iso: not be able to contact this server. Please configure a static IP address on
    vmware-iso: this computer before installing DNS Server.
    vmware-iso: True    No             Success        {DNS Server, DNS Server Tools}
    vmware-iso: True    No             NoChangeNeeded {}
```

**Comment by cbednarski** [comment]
It looks like the inline powershell script is being written out with batch-style environment variables.

**Comment by shannonlowder** [comment]
I'm getting the issue with my powershell provisioners too. I'm calling script files instead of inline.
```
{
		"type": "powershell",
		"scripts":[
			"./scripts/chocolatey.ps1"
		]
	},{
		"type": "powershell",
		"scripts":[
			"./scripts/OGSysInstaller_1.ps1",
			"./scripts/OGSysInstaller_2.ps1"
		]
	}
```

**Comment by simonguest** [comment]
I've tried similar configurations with both inline and script-based powershell commands, and get the same "warning" generated. It looks like packer is trying to prepend some kind of environment variable for PACKER_BUILDER_TYPE before the script is run. Also running Fusion 8.

**Comment by mwhooker** [comment]
Reopening since we reverted #3371

**Comment by Constantin07** [comment]
Hi,

I'm facing the same issue despite the powershell script works absolutely fine when run from Windows command line (or PSE).

```
    amazon-ebs: = : The term '=' is not recognized as the name of a cmdlet, function, script
    amazon-ebs: file, or operable program. Check the spelling of the name, or if a path was
    amazon-ebs: included, verify that the path is correct and try again.
    amazon-ebs: At line:1 char:4
    amazon-ebs: + &{ = amazon-ebs; =amazon-ebs; c:/Windows/Temp/script.ps1
    amazon-ebs: https://abasa-web-sup ...
    amazon-ebs: +    ~
    amazon-ebs: + CategoryInfo          : ObjectNotFound: (=:String) [], CommandNotFoundEx
    amazon-ebs: ception
    amazon-ebs: + FullyQualifiedErrorId : CommandNotFoundException
    amazon-ebs:
```

```
# packer.io version
Packer v1.1.0-dev
```
