### ISSUE TITLE
Trivial ansible-remote script does not work with AWS builder

### ISSUE THREAD

**Issue by pa-jama** [hashicorp/packer#5278]
My playbook works fine if I manually run it.
However packer tries to run it on 127.0.0.1 and it can't handshake?

Packer v1.0.4

[Full Log](https://gist.github.com/pa-jama/f7d5670c4782f7e3c197b0a09957e7da)

```
{
  "builders": [{
    "type": "amazon-ebs",
    "profile": "{{user `aws_profile`}}",
    "source_ami": "ami-e2021d81",
    "instance_type": "t2.micro",
    "ssh_username": "ubuntu",
    "ami_name": "appserver {{timestamp}}"
  }],
  "provisioners": 
  [{
    "type": "ansible",
    "user": "ubuntu",
    "playbook_file": "playbooks/all.yml",
    "groups": ["ubuntu16"],
    "extra_arguments": ["-vvvv"]
  }]
}

```
```
- hosts: ubuntu16
  become: true
  become_method: sudo
  become_user: root
  roles:
    - sysupdate
    - bootstrap/ubuntu
    - users
    - install/haproxy
    - utils

```
