### ISSUE TITLE
#5573 (path validation) prevents the use of multi-step builds

### ISSUE THREAD

**Issue by ferrarimarco** [hashicorp/packer#5727]
# Description of the problem

With the changes in #5573 it's not possible to validate a multi-step build anymore.

In my builds I usually split time-consuming tasks. With this strategy, if something goes wrong in any given step, I don't waste the work done in the previous steps.

Example: if I want to configure a VM with Ansible, I can run (each point is a separate `packer build -only=builder-name template.json` command):

1. Install the OS: `packer build -only=install-os template.json`
2. Install Ansible: `packer build -only=install-ansible template.json`
3. Run Ansible: `packer build -only=configure-ansible template.json`

In my CI builds I want to check if the packer template is valid, but I had to disable this check because of this issue.

# Environment

- Packer version from `packer version`: 1.1.3
- Host platform: Windows 10, Ubuntu 17.10

# Log

- Debug log output from `PACKER_LOG=1 packer build template.json`: [Here is a Travis CI build](https://travis-ci.org/ferrarimarco/open-development-environment-devbox/builds/318175840)

# How to reproduce

1. Run `packer validate` against:

```yaml
{
  "builders": [
    {
      "iso_urls": [
        "http://releases.ubuntu.com/17.04/ubuntu-17.04-server-amd64.iso"
      ],
      "name": "install-os",
      "output_directory": "builds/virtualbox-iso/{{user `template`}}",
      "type": "virtualbox-iso"
    },
    {
      "name": "install-ansible",
      "output_directory": "builds/virtualbox-ovf/provision-install-ansible/{{user `template`}}",
      "source_path": "builds/virtualbox-iso/{{user `template`}}/{{user `vm_name`}}.ovf",
      "type": "virtualbox-ovf"
    },
    {
      "name": "configure-ansible",
      "output_directory": "builds/virtualbox-ovf/configure-ansible/{{user `template`}}",
      "source_path": "builds/virtualbox-ovf/configure-ansible/{{user `template`}}/{{user `vm_name`}}.ovf",
      "type": "virtualbox-ovf"
    }
  ],
  "variables": {
    "template": "ubuntu-17.04-amd64",
    "vm_name": "open-development-environment-devbox-build"
  }
}
```
