### ISSUE TITLE
packer ansible + windows not working for me 

### ISSUE THREAD

**Issue by Strijd** [hashicorp/packer#7000]
packer version: 1.3.2 
ansible_version: 2.7 

I'm trying miserably to make packer provision windows machine on aws via ansible with no success. 

Steps
- packer 

```
[{
  "variables": {
    "aws_access_key": "{{ env `access_key` }}",
    "aws_secret_key": "{{ env `secret_key` }}",
    "aws_region": "us-east-1",
    "aws_instance_type": "t2.small",
    "image_version" : "latest"
  },
  "builders": [
    {
      "type": "amazon-ebs",
      "vpc_id": "vpc-xxx",
      "access_key": "{{user `aws_access_key`}}",
      "secret_key": "{{user `aws_secret_key`}}",
      "region": "{{user `aws_region`}}",
      "source_ami": "{{user `aws_ami_image`}}",
      "instance_type": "{{user `aws_instance_type`}}",
      "communicator": "winrm",
      "winrm_username": "<some_user>",
      "winrm_password": "<some_password>",
      "winrm_use_ssl": true, 
      "winrm_insecure": true,
      "winrm_port": "5986",
      "ami_name": "WinServer2012R2",
      "subnet_id": "subnet-xxx",
      "security_group_id": "sg-xxxx",
      "source_ami_filter": {
          "filters": {
            "name": "WinServer2012R2-*"
           },
          "owners": "xxxxxx",
          "most_recent": true
      },
      "tags": {
        "Name": "WinServer2012R2",
        "Version": "{{ user `image_version` }}",
        "Description": "{{ user `ami_name` }} image"
      }
    }
  ],
    
  "provisioners": [
    {
      "type": "ansible",
      "playbook_file": "./amz-windows.yml",
      "extra_arguments" : [
        "--connection", "packer", "-vvv"
      ]
    }
   ]
}
](url)

```
```
- hosts: all
  gather_facts: True
  vars:
     win_updates_category_names: ['CriticalUpdates','SecurityUpdates']
  tasks:
      - block:
          - name: Installing Security Updates |Windows[sux]
            win_updates:
               category_names: "{{ win_updates_category_names }}"
               log_path: D:\win_updates.log
            register: win_updates_result
            failed_when: win_updates_result.failed is defined and win_updates_result.failed
            ignore_errors: true

          - name: "Reboot Windows to re-try update installation."
            win_reboot:
               shutdown_timeout_sec: 3600
               reboot_timeout_sec: 3600

          - name: "Install Windows updates again."
            win_updates:
              category_names: "{{ win_updates_category_names }}"
            register: win_updates_result
            ignore_errors: true

          - name: "Install Windows updates again + again"
            win_updates:
              category_names: "{{ win_updates_category_names }}"
            register: win_updates_result
            ignore_errors: true

          - name: Fetch the update log file
            fetch:
              src: D:\win_updates.log
              dest: /tmp/win_updates.log
              flat: yes
        when: ansible_os_family == "Windows"

```

acording to the docs:
`any remote_user defined in tasks will be ignored. Packer will always connect with the user given in the json config for this provisioner.`
However, debugging the issue shows  ansible using my shell "username":
```

  amazon-ebs: ansible-playbook 2.7.0
    amazon-ebs:   config file = /etc/ansible/ansible.cfg
    amazon-ebs:   configured module search path = [u'/home/raid/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
    amazon-ebs:   ansible python module location = /home/toluna/ansible/ansible_2.4/lib/python2.7/site-packages/ansible
    amazon-ebs:   executable location = /home/toluna/ansible/ansible_2.4/bin/ansible-playbook
    amazon-ebs:   python version = 2.7.15 (default, Jun 27 2018, 13:05:28) [GCC 8.1.1 20180531]
    amazon-ebs: Using /etc/ansible/ansible.cfg as config file
    amazon-ebs: Parsed /tmp/packer-provisioner-ansible072771349 inventory source with ini plugin
    amazon-ebs:
    amazon-ebs: PLAYBOOK: amz-windows.yml ******************************************************
    amazon-ebs: 1 plays in /home/toluna/packer/aws/amz-windows/amz-windows.yml
    amazon-ebs:
    amazon-ebs: PLAY [all] *********************************************************************
    amazon-ebs:
    amazon-ebs: TASK [Gathering Facts] *********************************************************
    amazon-ebs: task path: /home/toluna/packer/aws/amz-windows/amz-windows.yml:1
    amazon-ebs: Using module file /home/toluna/ansible/ansible_2.4/lib/python2.7/site-packages/ansible/modules/windows/setup.ps1
    amazon-ebs: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: raid
    amazon-ebs: fatal: [default]: FAILED! => {
    amazon-ebs:     "msg": "Unhandled exception when retrieving use_tty:\nTraceback (most recent call last):\n  File \"/home/toluna/ansible/ansible_2.4/lib/python2.7/site-packages/ansible/config/manager.py\", line 350, in get_config_value\n    keys=keys, variables=variables, direct=direct)\n  File \"/home/toluna/ansible/ansible_2.4/lib/python2.7/site-packages/ansible/config/manager.py\", line 372, in get_config_value_and_origin\n    defs = self._plugins[plugin_type][plugin_name]\nKeyError: 'connection'\n"
    amazon-ebs: }
    amazon-ebs:
    amazon-ebs: PLAY RECAP *********************************************************************
    amazon-ebs: default                    : ok=0    changed=0    unreachable=0    failed=1

```
I also tried using ansible_envs_vars and --extra_vars and got the same result
Any ideas
Thanks
