### ISSUE TITLE
Feature Request; LXD metadata templates

### ISSUE THREAD

**Issue by Dan-Wolfy** [hashicorp/packer#7376]
Hi all,

Sorry if my google/github-fu is weak, but I am trying to use packer to build to LXD images with cloud-init and believe I need to enable templates within the metadata.yaml. So this is a feature request to add the templates sections to the metadata.yaml and to create the templates within image/templates folder.

LXD Docs; https://github.com/lxc/lxd/blob/master/doc/image-handling.md

Example templates;-
```
templates:
    /etc/hostname:
        when:
            - create
            - copy
        template: hostname.tpl
    /var/lib/cloud/seed/nocloud-net/meta-data:
        when:
            - create
            - copy
        template: cloud-init-meta.tpl
    /var/lib/cloud/seed/nocloud-net/network-config:
        when:
            - create
            - copy
        template: cloud-init-network.tpl
    /var/lib/cloud/seed/nocloud-net/user-data:
        when:
            - create
            - copy
        template: cloud-init-user.tpl
        properties:
            default: |
                #cloud-config
                {}
    /var/lib/cloud/seed/nocloud-net/vendor-data:
        when:
            - create
            - copy
        template: cloud-init-vendor.tpl
        properties:
            default: |
                #cloud-config
                {}
```

templates folder;-
```
vagrant@vagrant-test:/lxd/storage_pool_btrfs/images/35f6bff57c250208c6dc73445eefe8c1020853a1bc8571ebd8bfb1fe3a239504/templates$ ls
cloud-init-meta.tpl  cloud-init-network.tpl  cloud-init-user.tpl  cloud-init-vendor.tpl  hostname.tpl
vagrant@vagrant-test:/lxd/storage_pool_btrfs/images/35f6bff57c250208c6dc73445eefe8c1020853a1bc8571ebd8bfb1fe3a239504/templates$ cat cloud-init-meta.tpl 
instance-id: {{ container.name }}
local-hostname: {{ container.name }}
{{ config_get("user.meta-data", "") }}
vagrant@vagrant-test:/lxd/storage_pool_btrfs/images/35f6bff57c250208c6dc73445eefe8c1020853a1bc8571ebd8bfb1fe3a239504/templates$ cat cloud-init-network.tpl 
{% if config_get("user.network-config", "") == "" %}version: 1
config:
    - type: physical
      name: eth0
      subnets:
          - type: {% if config_get("user.network_mode", "") == "link-local" %}manual{% else %}dhcp{% endif %}
            control: auto{% else %}{{ config_get("user.network-config", "") }}{% endif %}
vagrant@vagrant-test:/lxd/storage_pool_btrfs/images/35f6bff57c250208c6dc73445eefe8c1020853a1bc8571ebd8bfb1fe3a239504/templates$ cat cloud-init-user.tpl 
{{ config_get("user.user-data", properties.default) }}
vagrant@vagrant-test:/lxd/storage_pool_btrfs/images/35f6bff57c250208c6dc73445eefe8c1020853a1bc8571ebd8bfb1fe3a239504/templates$ cat cloud-init-vendor.tpl 
{{ config_get("user.vendor-data", properties.default) }}
```
