### ISSUE TITLE
packer keeps skipping ansible task

### ISSUE THREAD

**Issue by e-moshaya** [hashicorp/packer#7388]
I am passing --extra-vars arango_cluster=false to packer ansible provisioner which should run the task below. This works absolutely fine in test kitchen. However, in Packer it keeps skipping the task with:

```
    Amazon-Linux-2: TASK [arangodb-ansible-role : debug] *******************************************
    Amazon-Linux-2: task path: /Users/emoshaya/Documents/GitHub/ansible-role-for-arangodb-ansible-role/roles/arangodb-ansible-role/tasks/main.yml:20
    Amazon-Linux-2: ok: [default] => {
    Amazon-Linux-2:     "msg": "arango_cluster is set to false"
    Amazon-Linux-2: }
Amazon-Linux-2: TASK [arangodb-ansible-role : Install Configuration] ***************************
    Amazon-Linux-2: task path: /Users/emoshaya/Documents/GitHub/ansible-role-for-arangodb-ansible-role/roles/arangodb-ansible-role/tasks/main.yml:23
    Amazon-Linux-2: skipping: [default] => {
    Amazon-Linux-2:     "changed": false,
    Amazon-Linux-2:     "skip_reason": "Conditional result was False"
```

```
- name: Install Configuration
  template:
    src: arangod.conf.j2
    dest: /etc/arangodb3/arangod.conf
    owner: arangodb
    group: arangodb
    mode: 0644
  notify: restart arangodb
  when: not arango_cluster
```

**Comment by vhaidamaka** [comment]
@e-moshaya According to [Ansible Documenation - Using Variables](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#passing-variables-on-the-command-line):
> Values passed in using the `key=value` syntax are interpreted as strings. Use the JSON format if you need to pass in anything that shouldn’t be a string (Booleans, integers, floats, lists etc).`

Passing `"extra_arguments": [ "--extra-vars", "'{\"myvar\":\"false\"}'"]` with escaped JSON data is not recognized by ansible:
```
==> vagrant: Executing Ansible: ansible-playbook --extra-vars packer_build_name=vagrant packer_builder_type=vagrant -o IdentitiesOnly=yes -i /tmp/packer-provisioner-ansible942132066 /home/gnat/local/src/packer-d
ebian-9/ansible/playbook.yml -e ansible_ssh_private_key_file=/tmp/ansible-key812238927 --extra-vars '{"myvar":"false"}'                                                                                            
    vagrant:                                                                                                                                                                                                       
    vagrant: PLAY [localhost] ***************************************************************                                                                                                                      
    vagrant:                                                                                                                                                                                                       
    vagrant: TASK [Gathering Facts] *********************************************************                                                                                                                      
    vagrant: ok: [localhost]                                                                                                                                                                                       
    vagrant:
    vagrant: TASK [debug] *******************************************************************
    vagrant: fatal: [localhost]: FAILED! => {"msg": "The conditional check 'myvar == \"false\"' failed. The error was: error while evaluating conditional (myvar == \"false\"): 'myvar' is undefined\n\nThe error a
ppears to have been in '/home/gnat/local/src/packer-debian-9/ansible/playbook.yml': line 16, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be
:\n\n\n    - debug:\n      ^ here\n"}

```

As a solution, you can change _when statement_ for your task:
```
- name: Install Configuration
  template:
    src: arangod.conf.j2
    dest: /etc/arangodb3/arangod.conf
    owner: arangodb
    group: arangodb
    mode: 0644
  notify: restart arangodb
  when: arango_cluster != "false"
```

@SwampDragons Maybe, it would be good idea to pass an optional parameter `vars_file` (JSON or YAML format) with extra variables?
