### ISSUE TITLE
Ansible local provisioner does not process well the "~" sign from the play

### ISSUE THREAD

**Issue by Ivasan7** [hashicorp/packer#7806]
I am using Ansible local as a provisioner for packer. The ~ sign not evaluated well to `/home/<username>`, but to `~<username`.

- Packer version from `Packer v1.4.2`
- Ubuntu 18.04 x86_64
- Debug log output:
```
azure-arm: fatal: [default]: FAILED! => {"changed": false, "checksum": "de599e18447156695c5e65619da0d08726edea41", "msg": "Destination directory ~ubuntu/.ssh does not exist"}

```
Reproduction steps:

1. Run a simple ubuntu deployment ( I have used Azure)
2. Choose provisioner Ansible local, `"ansible_user":"ubuntu"`
3. Run the following simple script:
```
- name: Place private key
  template:
    src: templates/id_rsa.openssh.j2
    dest: "~/.ssh/id_rsa"
    mode: 0400
  become: n
```
  NOTE: Workaround exists by replacing `~` with `${HOME}`.

**Comment by mgutha** [comment]
I think you may want to look at `Using HOME Variable` 
https://packer.io/docs/templates/user-variables.html

**Comment by SwampDragons** [comment]
This seems like an Ansible issue, not a Packer issue. If you're having trouble getting Ansible set up, I'd recommend reaching out to the [mailing list](https://groups.google.com/forum/#!forum/packer-tool) or the [community page](https://learn.hashicorp.com/packer/)

**Comment by Ivasan7** [comment]
@SwampDragons I have been using the ansible script for a while now and it is working, recently started working with packer and it only does not work in the context of packer provisioner. I think the issue is somehow connected to packer.

**Comment by SwampDragons** [comment]
If you want help investigating this, I need a full repro case including your packer template, not just the ansible script.

**Comment by Ivasan7** [comment]
So I have image.json file:
```
{
    "variables":{
    "vault_client_id": "",
    "vault_client_secret": "",
    "vault_tenant_id": "",
    "vault_subscription_id": "",
    "image_name":"",
    "image_size":"",
    "storage_type":""
    },

    "builders": [{
    "type": "azure-arm",

    "client_id": "{{user `vault_client_id`  }}",
    "client_secret": "{{user `vault_client_secret`  }}",
    "tenant_id": "{{user `vault_tenant_id` }}",
    "subscription_id": "{{user `vault_subscription_id` }}",

    "managed_image_resource_group_name": "test",
    "managed_image_name": "{{user `image_name` }}",

    "os_type": "Linux",
    "image_publisher": "Canonical",
    "image_offer": "UbuntuServer",
    "image_sku": "18.04-LTS",

    "azure_tags": {
        "dept": "Engineering",
        "task": "Image deployment"
    },

    "location": "West Europe",
    "vm_size": "{{user `image_size` }}",
    "managed_image_storage_account_type":"{{user  `storage_type` }}",
    "os_disk_size_gb":"30"
  }],
  "provisioners": [
    {
     "type": "ansible",
     "playbook_file": "main.yaml",
                                                                                                                                                       
"user": "ubuntu"
    },   
    {
      "execute_command": "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'",
      "inline": [
      "/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync"
      ],
      "inline_shebang": "/bin/sh -x",
      "type": "shell"
   }
  ]
}
```

Ansible file 
```
---
- name: Create .ssh directory if it doesn't exist
  file:
    path: "~/.ssh"
    state: directory
    mode: 0700
  become: no

- name: Place private key
  template:
    src: templates/id_rsa.j2
    dest: "~/.ssh/id_rsa"
    mode: 0400
  become: no
```
id_rsa content:
```public_key```

Call it by:
` packer build -force -var image_name=test -var image_size=Standard_D2s_v3 -var storage_type=Premium_LRS <add your creditentals here> image.json
