### ISSUE TITLE
Support for AWS SSM Session Manager

### ISSUE THREAD

**Issue by e-moshaya** [hashicorp/packer#8242]
Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-getting-started-enable-ssh-connections.html

#### Feature Description

Due to security, we disabled all SSH 22 ports on aws have switched to session manager. We would like to utilise session manager for connections to our packer instances. The way this would work would be to extend ssh_interface to return the instance id, so instead of "private_ip" we would set ssh_interface: "id".

#### Use Case(s)

https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-getting-started-enable-ssh-connections.html

test-kitchen https://github.com/test-kitchen/kitchen-ec2 has already been updated to support session manager so it would be great if packer can support too.

**Comment by rickard-von-essen** [comment]
This would require a new `communicator`. A good start is the [SSM API Docs - StartSession](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_StartSession.html).

**Comment by e-moshaya** [comment]
@rickard-von-essen this does not need a new communicator at all. We can still use ssh to connect over ssh. The changes should be very minor.

From the client's side, we just need to add the following to ~/.ssh/config based on aws [documentation](https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-getting-started-enable-ssh-connections.html):

```
# SSH over Session Manager
host i-* mi-*
    ProxyCommand sh -c "aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters 'portNumber=%p'"
```
Please check the change the ec2 driver for the test kitchen framework made to support ssm"

https://github.com/test-kitchen/kitchen-ec2/pull/461

My .kitchen.yml template is, with the transport still set to ssh. Only change is I changed the ssh interface from private_ip to id:

```
---
driver:
  name: ec2
  aws_ssh_key_id: test-kitchen
  instance_type: t3.small
  security_group_filter:
    tag:   'Name'
    value: 'kitchen-instance'
  region: eu-west-2
  subnet_filter:
    tag:   'Name'
    value: 'syn-ci-cd-private'
  iam_profile_name: test-kitchen
  instance_initiated_shutdown_behavior: terminate
  interface: id
  tags: { created-by: "test-kitchen",
          Owner: "Jenkins" }
  image_search:
    owner-id: "137112412989"
    name: amzn2-ami-hvm-*gp2

transport:
  ssh_key: ~/.ssh/test-kitchen.pem
  connection_timeout: 10
  connection_retries: 5
  username: ec2-user
  keepalive: true
  name: ssh
  max_ssh_sessions: 2

provisioner:
  name: ansible_playbook
  playbook: test/default.yml
  roles_path: ../../roles
  hosts: all
  require_ansible_repo: false
  require_ansible_omnibus: false
  require_chef_omnibus: false
  ansible_verbose: true
  idempotency_test: false
  ansible_diff: true
  max_retries: 2
  require_chef_for_busser: true
  require_pip: true
  enable_yum_epel: true
  requirements_path: "requirements.yml"
  ssh_known_hosts: ["github.com"]

verifier:
  sudo_path: true

platforms:
- name: amazon-linux

suites:
  - name: default
```
