### ISSUE TITLE
shared_image_gallery_destination timeout issue

### ISSUE THREAD

**Issue by jontreynes** [hashicorp/packer#8445]
I am using Azure DevOps task, [PackerBuild@1](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/packer-build?view=azure-devops), with a customTemplate to build my image. The task runs successfully without shared_image_gallery_destination resource.

When I add the below code
`      "shared_image_gallery_destination": {

        "resource_group":"myrg",

        "gallery_name": "mygallery",

        "image_name": "myimage",

        "image_version": "3.0.0",

        "replication_regions": ["eastus"]

    },`
I receive the below timeout error

`Build 'azure-arm' errored: Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded`

using version 1.4.5 like so:

``` 
- task: PackerBuild@1
      condition: true
      displayName: Build ${{ job.ibb_dest_sig_definition }} Custom Image
      inputs:
        templateType: 'custom'
        customTemplateLocation: '${{ job.ibb_customTemplateLocation }}'
        customTemplateParameters: # params
        connectedServiceName: ${{parameters.ibb_service_connection}}
        packerVersion: '1.4.5'
```
