### ISSUE TITLE
max_reteries not working in shell for vsphere-iso provider

### ISSUE THREAD

**Issue by thatsk** [hashicorp/packer#9227]
#### Overview of the Issue
try to run puppet on node first time it fails but second time succeed, so we have to run script two time if it first fails so try to use type shell for running puppet on newly baked system.

### Packer version
1.5.5

### Simplified Packer Buildfile
```YAML
{
  "variables": {
    "build_number": "{{timestamp}}",
    "centos_arch": "x86_64",
    "iso_base_url": "http://mirror.cs.vt.edu/pub/CentOS",
    "iso_checksum_type": "sha256",
    "username": "root",
    "password": "J@",
    "vm-cpu-num": "2",
    "vm-mem-size": "8192",
    "vm-disk-size": "122880",
    "timeout": "30m",
    "vm-name": "{{user `nodetype` }}",
    "centos_version": "7",
    "ks_file": "centos7.cfg",
    "iso_filename": "Minimal-1908",
    "iso_checksum": "9a2c47d97b9975452f7d582264e9fc16d108ed8252ac6816239a3b58cef5c53d"
  },
"builders": [{
    "type": "vsphere-iso",
    "iso_url": "{{user `iso_base_url`}}/{{user `centos_version`}}/isos/{{user `centos_arch`}}/CentOS-{{user `centos_version`}}-{{user `centos_arch`}}-{{user `iso_filename`}}.iso",
    "iso_checksum": "{{user `iso_checksum`}}",
    "vcenter_server": "{{user `vsphere-server`}}",
    "username": "{{user `vsphere-user`}}",
    "password": "{{user `vsphere-password`}}",
    "insecure_connection": "true",
    "datacenter": "{{user `vsphere-datacenter`}}",
    "cluster": "{{user `vsphere-cluster`}}",
    "network": "{{user `vsphere-network`}}",
    "datastore": "{{user `vsphere-datastore`}}",
    "vm_name": "{{user `vm-name`}}",
    "guest_os_type": "rhel7_64Guest",
    "vm_version" : 11,

    "ssh_username": "{{user `username`}}",
    "ssh_password": "{{user `password`}}",
    "CPUs": "{{user `vm-cpu-num`}}",
    "RAM": "{{user `vm-mem-size`}}",
    "convert_to_template": true,
    "disk_size": "{{user `vm-disk-size`}}",
    "disk_thin_provisioned": true,
    "disk_controller_type": "pvscsi",
    "network_card": "vmxnet3",
    "shutdown_command": "shutdown -P now",
    "boot_wait": "10s",
    "boot_order": "cdrom,ethernet,disk",
   "iso_paths": "[{{user `vsphere-datastore`}}] ISO/CentOS.iso,[{{user `vsphere-datastore`}}] ISO/kickstart.iso"
   }],
  "provisioners": [{
      "type": "shell",
      "script": "scripts/base.sh",
       "timeout": "100s"
    },
    {
      "type": "shell",
      "script": "scripts/vmware-tools.sh",
      "timeout": "100s"
    },
    {
      "type": "shell",
      "script": "scripts/cleanup.sh",
      "timeout": "100s"
    },
    {
      "type": "shell",
      "environment_vars": ["ipaserver={{user `ipaserver` }}",
                           "realm={{user `realm` }}",
                           "hostname={{user `hostname` }}",
                           "domain={{user `domain` }}"
                           ],
      "script": "scripts/ipa-join.sh",
      "timeout": "400s"
    },
    {
      "type": "shell",
      "script": "scripts/puppet.sh",
      "timeout": "400s",
      "max_retries": 3
    }
 ]
 }
```
### Operating system and Environment details
centos7
```YAML
packer validate -var "nodetype=mi" -var-file=variables.json packer.json
```
Template validation failed. Errors are shown below.
```YAML
Errors validating build 'vsphere-iso'. 1 error occurred:
        * unknown configuration key: "max_retries"; raws is []interface {}{map[string]interface {}{"max_retries":3, "script":"scripts/puppet.sh"}, map[string]interface {}{"packer_build_name":"vsphere-iso", "packer_builder_type":"vsphere-iso", "packer_debug":false, "packer_force":false, "packer_on_error":"", "packer_template_path":"/home/kthakur/packer/centos7/medium/packer.json", "packer_user_variables":map[interface {}]interface {}{"":"", "build_number":"1589468849", "centos_arch":"x86_64", "centos_version":"7", "iso_base_url":"http://mirror.cs.vt.edu/pub/CentOS", "iso_checksum":"9a2c47d97b9975452f7d582264e9fc16d108ed8252ac6816239a3b58cef5c53d", "iso_checksum_type":"sha256", "iso_filename":"Minimal-1908", "ks_file":"centos7.cfg", "nodetype":"mi", "password":"J@", "timeout":"30m", "username":"root", "vm-cpu-num":"2", "vm-disk-size":"122880", "vm-mem-size":"8192", "vm-name":"mi", "vsphere-cluster":"Dev", "vsphere-datacenter":"kfe", "vsphere-datastore":"datastore1 (1)", "vsphere-network":"VM-68 Network", "vsphere-password":"!", "vsphere-server":"inv", "vsphere-user":"devop"}}}

 and ctx data is map[interface {}]interface {}{"ConnType":"Build_Type. To set this dynamically in the Packer template, you must use the `build` function", "Host":"Build_Host. To set this dynamically in the Packer template, you must use the `build` function", "ID":"Build_ID. To set this dynamically in the Packer template, you must use the `build` function", "PackerHTTPAddr":"Build_PackerHTTPAddr. To set this dynamically in the Packer template, you must use the `build` function", "PackerRunUUID":"Build_PackerRunUUID. To set this dynamically in the Packer template, you must use the `build` function", "Password":"Build_Password. To set this dynamically in the Packer template, you must use the `build` function", "Port":"Build_Port. To set this dynamically in the Packer template, you must use the `build` function", "SSHPrivateKey":"Build_SSHPrivateKey. To set this dynamically in the Packer template, you must use the `build` function", "SSHPublicKey":"Build_SSHPublicKey. To set this dynamically in the Packer template, you must use the `build` function", "User":"Build_User. To set this dynamically in the Packer template, you must use the `build` function", "WinRMPassword":"{{.WinRMPassword}}"}
```
