### ISSUE TITLE
Accept `user-data` as a json object

### ISSUE THREAD

**Issue by curiositycasualty** [hashicorp/packer#9235]
#### Feature Description
The amazon-* builders only accept `user-data` as a string. I'd much prefer if packer accepted a json object and rendered it as a string for AWS's sake OR explicitly accepted a "cloud_init_user_data" param that would render as yaml (including the mandatory first "#cloud-config" line). Do so would force JSON compliance on the contents of the param and aid in `cloud-init` configuration.

**Comment by SwampDragons** [comment]
Hi Isa! Nice to see you again. 

I agree this would be a big improvement for usability but am not sure when we'll get around to it -- however, you may find that using the [user_data_file](https://www.packer.io/docs/builders/amazon-ebs.html#user_data_file) option, which does allow you to write true JSON, allows you some more readability and flexibility in the meantime.

**Comment by curiositycasualty** [comment]
For my use case, there's a slew of `user` variables throughout my user-data that I need the templating engine for when I don't think the templating engine renders out a `user_data_file`.

**Comment by SwampDragons** [comment]
Good point.

**Comment by curiositycasualty** [comment]
I guess I can elaborate on my use case. Here's a sanitized example with the caveat that I use a nodejs tool to consume the yaml and emit a json template for packer. The crucial bit being the `user-data: |` which forfeits any validation that could be done on the cloud-init "script"-- even though it's just json/yaml.

```yaml
---
builders:
  - &tmpl
    name: template
    type: amazon-ebs
    # <snip>
    # Canonical's Ubuntu
    source_ami_filter:
      filters:
        architecture: x86_64
        name: ubuntu/images/*{{user `ubuntu_version`}}-amd64-server-*
        root-device-type: ebs
        virtualization-type: hvm
      most_recent: true
      owners:
        - '099720109477'
    # <snip>
    user_data: |
      #cloud-config
      apt:
        sources:
          adoptopenjdk.list:
            keyid: 8AC3B29174885C03
            source: "deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ $RELEASE main"
      users:
        - default
        - name: {{user `app_user`}}
          homedir: {{user `app_install_root`}}
          no_create_home: true
          shell: /bin/bash
      timezone: UTC
      package_update: true
      package_upgrade: true
      package_reboot_if_required: false
      packages:
        # JDK(s)
        - adoptopenjdk-11-hotspot
        - adoptopenjdk-{{user `jvm_version`}}-hotspot

        # compilation support
        - build-essential
        - libbz2-dev
        - libffi-dev
        - liblzma-dev
        - libncurses5-dev
        - libreadline-dev
        - libsqlite3-dev
        - libssl-dev
        - libxml2-dev
        - libxmlsec1-dev
        - zlib1g-dev

        # general packages
        - awscli
        - curl
        - docker.io
        - gawk
        - git
        - jq
        - make
        - psmisc
        - python3-pip
        - sed
        - shellcheck
        - sl
        - subversion
        - tree
        - unzip
        - wget

      write_files:
        - content: |
            [Unit]
            Description=App
            After=network.target
            [Service]
            Type=forking
            RemainAfterExit=yes
            User={{user `app_user`}}
            Group={{user `app_user`}}
            PIDFile={{user `app_install_root`}}/logs/app.pid
            Environment="JAVA_HOME=/usr/lib/jvm/adoptopenjdk-{{user `jvm_version`}}-hotspot-amd64"
            ExecStart={{user `app_install_root`}}/bin/app.sh start
            ExecStop={{user `app_install_root`}}/bin/app.sh stop
            SuccessExitStatus=143 0
            [Install]
            WantedBy=multi-user.target
          path: /etc/systemd/system/app.service
        - content: |
            Host bastion
              HostName bastion.internal
              User ubuntu
          path: /tmp/ssh_config
      runcmd:
        # rm some unwanted packages
        - apt-get purge lxd lxd-client snapd
        - wget http://<snip>/app.zip
        - unzip app.zip -d {{user `app_install_root`}}
        # the user's home dir won't exist until unzip runs
        - cd {{user `app_install_root`}}
        # ssh
        - mkdir -pv .ssh
        - cp -v /tmp/ssh_config .ssh/config
        # App
        - cp -v conf/app.dist.properties conf/app.properties
        - chown -Rv {{user `app_user`}}:{{user `app_user`}} {{user `app_install_root`}}
        - systemctl daemon-reload
        - systemctl enable app.service
        # docker
        - systemctl enable --now docker
        - usermod -aG docker {{user `app_user`}}
    ssh_username: 'ubuntu'
    subnet_id: '{{user `subnet_id`}}'
```
