### ISSUE TITLE
Packer stuck after shell script 

### ISSUE THREAD

**Issue by Jordy694** [hashicorp/packer#9768]
After creating successfully an image with packer i want to use the shell script provisioner to install some packages like ansible and python. But after installing my shell hangs on:
```
    virtualbox-iso: debconf: falling back to frontend: Readline
    virtualbox-iso: Checking for services that may need to be restarted...done.
    virtualbox-iso: Checking for services that may need to be restarted...done.
    virtualbox-iso: Checking init scripts...
    virtualbox-iso: Configuring libssl1.1:amd64
    virtualbox-iso: ---------------------------
    virtualbox-iso:
    virtualbox-iso: There are services installed on your system which need to be restarted when
    virtualbox-iso: certain libraries, such as libpam, libc, and libssl, are upgraded. Since these
    virtualbox-iso: restarts may cause interruptions of service for the system, you will normally be
    virtualbox-iso: prompted on each upgrade for the list of services you wish to restart.  You can
    virtualbox-iso: choose this option to avoid being prompted; instead, all necessary restarts will
    virtualbox-iso: be done for you automatically so you can avoid being asked questions on each
    virtualbox-iso: library upgrade.
    virtualbox-iso:
```

My ubuntu.json file
```
{
    "builders": [
        {
            "type": "virtualbox-iso",
            "boot_command": [
                "<esc><wait>",
                "<esc><wait>",
                "<enter><wait>",
                "/install/vmlinuz<wait>",
                " auto<wait>",
                " console-setup/ask_detect=false<wait>",
                " console-setup/layoutcode=us<wait>",
                " console-setup/modelcode=pc105<wait>",
                " debconf/frontend=noninteractive<wait>",
                " debian-installer=en_US<wait>",
                " fb=false<wait>",
                " initrd=/install/initrd.gz<wait>",
                " kbd-chooser/method=us<wait>",
                " keyboard-configuration/layout=USA<wait>",
                " keyboard-configuration/variant=USA<wait>",
                " locale=en_US<wait>",
                " netcfg/get_domain=vm<wait>",
                " netcfg/get_hostname=ubuntu<wait>",
                " grub-installer/bootdev=/dev/sda<wait>",
                " noapic<wait>",
                " preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg<wait>",
                " -- <wait>",
                "<enter><wait>"
            ],
            "boot_wait": "10s",
            "disk_size": 81920,
            "guest_os_type": "Ubuntu_64",
            "headless": false,
            "http_directory": "http",
            "iso_urls": [
                "iso/ubuntu-18.04.1-server-amd64.iso",
                "http://old-releases.ubuntu.com/releases/bionic/ubuntu-18.04.1-server-amd64.iso"
            ],
            "iso_checksum": "a5b0ea5918f850124f3d72ef4b85bda82f0fcd02ec721be19c1a6952791c8ee8",
            "ssh_username": "ubuntu",
            "ssh_password": "ubuntu",
            "ssh_port": 22,
            "ssh_wait_timeout": "10000s",
            "shutdown_command": "echo 'ubuntu'|sudo -S shutdown -P now",
            "guest_additions_path": "VBoxGuestAdditions_{{.Version}}.iso",
            "virtualbox_version_file": ".vbox_version",
            "vm_name": "packer-ubuntu-18.04.1-amd64",
            "vboxmanage": [
            [
                "modifyvm",
                "{{.Name}}",
                "--memory",
                "1024"
            ],
            [
                "modifyvm",
                "{{.Name}}",
                "--cpus",
                "1"
            ]
            ]
        }
    ],
    "provisioners": [
        {
            "type": "shell",
            "script": "scripts/init.sh",
            "execute_command": "echo 'ubuntu' | {{.Vars}} sudo -S -E bash '{{.Path}}'",
            "pause_before": "10s",
            "timeout": "10s"
        },
        {
            "type": "shell-local",
            "script": "scripts/cleanup.sh",
            "execute_command": "echo 'ubuntu' | {{.Vars}} sudo -S -E bash '{{.Path}}'",
            "pause_before": "10s",
            "timeout": "10s"
        }    
    ]
  }
```

My init.sh script to install ansible and python.

```
:!/bin/sh

:Add ubuntu user to sudoers.
echo "ubuntu        ALL=(ALL)       NOPASSWD: ALL" >> /etc/sudoers
sed -i "s/^.*requiretty/#Defaults requiretty/" /etc/sudoers

: Disable daily apt unattended updates.
echo 'APT::Periodic::Enable "0";' >> /etc/apt/apt.conf.d/10periodic

apt update
apt-get install -y -qq git python python-dev
wget http://peak.telecommunity.com/dist/ez_setup.py
python ez_setup.py && rm -f ez_setup.py
easy_install pip
pip install setuptools --no-use-wheel --upgrade
pip install paramiko pyyaml jinja2 markupsafe
pip install ansible
exit 0
```

Can somebody help me out with this?
